package com.chen.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERSON.
 */
public class Person {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String mobile;
    private String age;
    private String sex;
    private String email;
    private String hometown;
    private String job;
    private String describe;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String name, String mobile, String age, String sex, String email, String hometown, String job, String describe) {
        this.id = id;
        this.name = name;
        this.mobile = mobile;
        this.age = age;
        this.sex = sex;
        this.email = email;
        this.hometown = hometown;
        this.job = job;
        this.describe = describe;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getMobile() {
        return mobile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getHometown() {
        return hometown;
    }

    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    @Override
    public String toString() {
        return "Person [id=" + id + ", name=" + name + ", mobile=" + mobile
                + ", age=" + age + ", sex=" + sex + ", email=" + email
                + ", hometown=" + hometown + ", job=" + job + ", describe="
                + describe + "]";
    }
    
    

}
