package com.chen.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table THREAD_INFO.
 */
public class ThreadInfo {

    private Long id;
    private Integer thread_id;
    private String url;
    private Integer start;
    private Integer end;
    private Integer finished;

    public ThreadInfo() {
    }

    public ThreadInfo(Long id) {
        this.id = id;
    }

    public ThreadInfo(Long id, Integer thread_id, String url, Integer start, Integer end, Integer finished) {
        this.id = id;
        this.thread_id = thread_id;
        this.url = url;
        this.start = start;
        this.end = end;
        this.finished = finished;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getThread_id() {
        return thread_id;
    }

    public void setThread_id(Integer thread_id) {
        this.thread_id = thread_id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

    public Integer getFinished() {
        return finished;
    }

    public void setFinished(Integer finished) {
        this.finished = finished;
    }

}
